apiVersion: v1
kind: ReplicationController
metadata:
  name: promotion
spec:
  replicas: 3
  selector:
    app: promotion
  template:
    metadata:
      name: promotion
      labels:
        app: promotion
    spec:
      containers:
        - name: promotion
          image: jorgesanzb/e-commerce-promotion:1.0.0
          ports:
            - containerPort: 8082