# Description: an example pipeline for a docker e-commerce application
# Version 1.0
name: CICD_PYTHON_ECS
on:
  push:

jobs:
  Init:
    name: Init
    runs-on:
      labels: self-hosted

    steps:
      - run: echo "Hello Cloud Gurus"
      - run: echo $HOSTNAME
      